# bai1
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler
print("===== SPORTS DATASET =====")
df = pd.read_csv("sports.csv")
df = df.select_dtypes(include=['number'])
print(df.describe())
df.hist(figsize=(10,8))
plt.suptitle("Sports - Before Scaling")
plt.show()
df.boxplot()
plt.title("Sports - Boxplot")
plt.show()
minmax = MinMaxScaler()
zscore = StandardScaler()
df_minmax = pd.DataFrame(minmax.fit_transform(df), columns=df.columns)
df_zscore = pd.DataFrame(zscore.fit_transform(df), columns=df.columns)
df_minmax.hist(figsize=(10,8))
plt.suptitle("Sports - MinMax")
plt.show()
df_zscore.hist(figsize=(10,8))
plt.suptitle("Sports - Z-score")
plt.show()
print("-->MinMax đưa dữ liệu về [0,1] nhưng nhạy với outlier, Z-score ổn định hơn")

#bai2
print("===== HEALTH DATASET =====")
df = pd.read_csv("health.csv")
df = df.select_dtypes(include=['number'])
print(df.describe())
df.boxplot()
plt.title("Health - Outliers")
plt.show()
df_minmax = pd.DataFrame(minmax.fit_transform(df), columns=df.columns)
df_zscore = pd.DataFrame(zscore.fit_transform(df), columns=df.columns)
df.hist(figsize=(10,8))
plt.suptitle("Health - Before")
plt.show()
df_minmax.hist(figsize=(10,8))
plt.suptitle("Health - MinMax")
plt.show()
df_zscore.hist(figsize=(10,8))
plt.suptitle("Health - Z-score")
plt.show()
print("--> Có nhiều outlier, inMax bị ảnh hưởng mạnh, Z-score xử lý tốt hơn")

#bai3
print("===== FINANCE DATASET =====")
df = pd.read_csv("finance.csv")
df = df.select_dtypes(include=['number'])
plt.scatter(df['Revenue'], df['Profit'])
plt.title("Before Scaling")
plt.show()
df_minmax = pd.DataFrame(minmax.fit_transform(df), columns=df.columns)
df_zscore = pd.DataFrame(zscore.fit_transform(df), columns=df.columns)
plt.scatter(df_minmax['Revenue'], df_minmax['Profit'])
plt.title("MinMax")
plt.show()
plt.scatter(df_zscore['Revenue'], df_zscore['Profit'])
plt.title("Z-score")
plt.show()
print("--> ó outlier lớn, MinMax làm mất phân bố, Z-score giữ mối quan hệ tốt hơn")

#bai4
print("===== GAMING DATASET =====")
df = pd.read_csv("gaming.csv")
df = df.select_dtypes(include=['number'])
print(df.describe())
df.boxplot()
plt.title("Gaming - Outliers")
plt.show()
df_minmax = pd.DataFrame(minmax.fit_transform(df), columns=df.columns)
df_zscore = pd.DataFrame(zscore.fit_transform(df), columns=df.columns)
df.hist(figsize=(10,8))
plt.suptitle("Gaming - Before")
plt.show()
df_minmax.hist(figsize=(10,8))
plt.suptitle("Gaming - MinMax")
plt.show()
df_zscore.hist(figsize=(10,8))
plt.suptitle("Gaming - Z-score")
plt.show()
print("--> Có người chơi nhiều bất thường, MinMax bị lệch, Z-score ổn định hơn")

